package com.ccatq.xdylupdater2.developer

val knownRoutes = listOf(
    KnownRoute("认证", "登录", "/login", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "刷新令牌", "/refresh", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "注册", "/register", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "忘记密码", "/forgot-password", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "重置密码", "/reset-password", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "发送验证码", "/send-verify-code", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "QQ 登录", "/qq-login", "GET", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("认证", "检查 QQ 登录", "/check-qq-login", "GET", false, "https://login.lanternwaves.fun", "session_id="),
    KnownRoute("认证", "通知登录", "/notify-login", "POST", false, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "个人资料", "/user/profile", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "更新资料", "/user/profile", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "上传头像", "/user/avatar", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "修改密码", "/user/password", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "修改用户名", "/user/change-username", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "绑定 QQ", "/user/bind-qq", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "解绑 QQ", "/user/unbind-qq", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "我的物品", "/user/items", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "表情", "/user/emojis", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("用户", "上传 YSM 皮肤", "/upload_v2", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "论坛分类", "/forum/categories", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "帖子列表", "/forum/posts", "GET", true, "https://login.lanternwaves.fun", "page=1"),
    KnownRoute("社区", "发布帖子", "/forum/post", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "帖子详情", "/forum/post/{id}", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "回复帖子", "/forum/post/{id}/reply", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "点赞帖子", "/forum/post/{id}/like", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "打赏帖子", "/forum/post/{id}/tip", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("社区", "上传图片", "/upload/image", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "周目", "/seasons", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "在线玩家", "/server/players", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "喵币排行", "/rank/coins", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "在线排行", "/rank/playtime", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "游戏奖励", "/playtime/rewards", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "领取游戏奖励", "/playtime/rewards/claim", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "任务", "/tasks", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "领取任务", "/tasks/{id}/claim", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "投票列表", "/polls", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("游戏", "投票", "/vote", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "我的排位", "/pvp/me", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "在线玩家", "/pvp/online", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "收到的挑战", "/pvp/incoming", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "游戏账号", "/pvp/accounts", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "当前匹配", "/pvp/match/status", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "排行榜", "/pvp/rank", "GET", true, "https://login.lanternwaves.fun", "limit=50"),
    KnownRoute("决斗场", "发起挑战", "/pvp/challenge", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "处理挑战", "/pvp/challenge/respond", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "开始匹配", "/pvp/match/join", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "确认对局", "/pvp/match/confirm", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("决斗场", "取消匹配", "/pvp/match/leave", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "商城物品", "/shop/items", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "购买商品", "/shop/buy", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "称号目录", "/titles/catalog", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "我的称号", "/titles/mine", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "购买称号", "/titles/buy", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "佩戴称号", "/titles/wear", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "兑换比例", "/redeem/rate", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("商城", "兑换游戏币", "/redeem/game-coins", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "公告", "/announcements", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "通知", "/notifications", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "未读通知数", "/notifications/unread", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "全部通知已读", "/notifications/read", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "意见箱", "/suggestions", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "提交意见", "/suggestions", "POST", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("内容", "纪念堂", "/memorials", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("更新", "最新更新", "/update/latest", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("更新", "整合包链接", "/update/pack-links", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("更新", "模组列表", "/mods/list", "GET", true, "https://login.lanternwaves.fun", ""),
    KnownRoute("资源", "公开模组清单", "/mods.json", "GET", false, "http://api.lanternwaves.fun:5551/mods/", ""),
)
